import type { NavItem } from "./types";

export const NAV_ITEMS: NavItem[] = [
  {
    title: "CEO Dashboard",
    href: "/ceo-dashboard",
    icon: "LayoutDashboard",
    description: "BUILD 009 Owner View",
  },
  {
    title: "Sales Command",
    href: "/sales-command-center",
    icon: "CalendarClock",
    description: "Dzienny pulpit sprzedaży",
  },
  {
    title: "Owner Cockpit",
    href: "/owner-cockpit",
    icon: "LayoutDashboard",
    description: "BUILD 010 Revenue OS",
  },
  {
    title: "Production OS",
    href: "/production-os",
    icon: "ShieldAlert",
    description: "BUILD 011 Production Operations",
  },
  {
    title: "Daily Brief",
    href: "/daily-brief",
    icon: "Award",
    description: "Poranny briefing CEO z rekomendacjami",
  },
  {
    title: "Marketing Command",
    href: "/marketing-command-center",
    icon: "Megaphone",
    description: "BUILD 012 Marketing Command Center",
  },
  {
    title: "Lead Intelligence",
    href: "/lead-intelligence",
    icon: "Users",
    description: "BUILD 013 Lead Intelligence Engine",
  },
  {
    title: "Magda Action Engine",
    href: "/magda-action-engine",
    icon: "CalendarClock",
    description: "BUILD 014 Dzienna egzekucja sprzedaży",
  },
  {
    title: "AI Revenue Manager",
    href: "/ai-revenue-manager",
    icon: "Award",
    description: "BUILD 015 Decyzje jak dowieźć plan",
  },
  {
    title: "Offer & Follow-up",
    href: "/offer-followup-engine",
    icon: "FileText",
    description: "BUILD 016 Kontrola ofert i follow-upów",
  },
  {
    title: "Lost Deal Analyzer",
    href: "/lost-deal-analyzer",
    icon: "SearchX",
    description: "BUILD 017 Analiza przegranych ofert",
  },
  {
    title: "Referral & Architect",
    href: "/referral-architect-engine",
    icon: "Users",
    description: "BUILD 018 Kanał poleceń i architektów",
  },
  {
    title: "Campaign ROI",
    href: "/campaign-roi-engine",
    icon: "LineChart",
    description: "BUILD 019 Odpowiedzialność kampanii reklamowych",
  },
  {
    title: "Executive Brief",
    href: "/executive-daily-brief",
    icon: "Crown",
    description: "BUILD 020 Poranny ekran dowodzenia CEO",
  },
  {
    title: "Data Discipline",
    href: "/data-discipline",
    icon: "ShieldAlert",
    description: "BUILD 014A Dyscyplina danych leadów",
  },
  {
    title: "Dashboard CEO",
    href: "/dashboard",
    icon: "LayoutDashboard",
    description: "Przegląd wykonawczy",
  },
  {
    title: "Leady",
    href: "/leads",
    icon: "Users",
    description: "Lejek sprzedażowy",
  },
  {
    title: "Oferty",
    href: "/offers",
    icon: "FileText",
    description: "Aktywne oferty",
  },
  {
    title: "Followupy",
    href: "/followups",
    icon: "CalendarClock",
    description: "Zaplanowane działania",
  },
  {
    title: "Handlowcy",
    href: "/salespeople",
    icon: "UserCheck",
    description: "Wyniki zespołu",
  },
  {
    title: "Modele",
    href: "/models",
    icon: "Home",
    description: "Katalog produktów",
  },
  {
    title: "M-Intelligence",
    href: "/marketing-intelligence",
    icon: "Megaphone",
    description: "Google & Meta Ads",
  },
  {
    title: "Wyciek Pieniędzy",
    href: "/money-leak",
    icon: "TrendingDown",
    description: "Utrata przychodów",
  },
  {
    title: "Martwe Leady",
    href: "/dead-leads",
    icon: "Skull",
    description: "Nieaktywne szanse",
  },
  {
    title: "Wynik CEO",
    href: "/ceo-score",
    icon: "Award",
    description: "Indeks kondycji",
  },
  {
    title: "Słowniki",
    href: "/dictionaries",
    icon: "ShieldAlert",
    description: "Handlowcy i modele",
  },
  {
    title: "Import CSV",
    href: "/import",
    icon: "Upload",
    description: "Importowanie leadów",
  },
];
