import type { NavItem } from "./types";

export const NAV_ITEMS: NavItem[] = [
  {
    title: "Pulpit CEO",
    href: "/ceo-dashboard",
    icon: "LayoutDashboard",
    description: "BUILD 009 Widok właściciela",
  },
  {
    title: "Centrum Sprzedaży",
    href: "/sales-command-center",
    icon: "CalendarClock",
    description: "Dzienny pulpit sprzedaży",
  },
  {
    title: "Kokpit Właściciela",
    href: "/owner-cockpit",
    icon: "LayoutDashboard",
    description: "BUILD 010 System przychodów",
  },
  {
    title: "System Produkcji",
    href: "/production-os",
    icon: "ShieldAlert",
    description: "BUILD 011 Operacje produkcyjne",
  },
  {
    title: "Poranny Brief",
    href: "/daily-brief",
    icon: "Award",
    description: "Poranny briefing CEO z rekomendacjami",
  },
  {
    title: "Centrum Marketingu",
    href: "/marketing-command-center",
    icon: "Megaphone",
    description: "BUILD 012 Centrum dowodzenia marketingu",
  },
  {
    title: "Inteligencja Leadów",
    href: "/lead-intelligence",
    icon: "Users",
    description: "BUILD 013 Silnik inteligencji Leadów",
  },
  {
    title: "Silnik Działań Magdy",
    href: "/magda-action-engine",
    icon: "CalendarClock",
    description: "BUILD 014 Dzienna egzekucja sprzedaży",
  },
  {
    title: "AI Manager Przychodów",
    href: "/ai-revenue-manager",
    icon: "Award",
    description: "BUILD 015 Decyzje jak dowieźć plan",
  },
  {
    title: "Oferty i Followupy",
    href: "/offer-followup-engine",
    icon: "FileText",
    description: "BUILD 016 Kontrola ofert i follow-upów",
  },
  {
    title: "Analiza Utraconych Ofert",
    href: "/lost-deal-analyzer",
    icon: "SearchX",
    description: "BUILD 017 Analiza przegranych ofert",
  },
  {
    title: "Polecenia i Architekci",
    href: "/referral-architect-engine",
    icon: "Users",
    description: "BUILD 018 Kanał poleceń i architektów",
  },
  {
    title: "ROI Kampanii",
    href: "/campaign-roi-engine",
    icon: "LineChart",
    description: "BUILD 019 Odpowiedzialność kampanii reklamowych",
  },
  {
    title: "Brief Zarządczy",
    href: "/executive-daily-brief",
    icon: "Crown",
    description: "BUILD 020 Poranny ekran dowodzenia CEO",
  },
  {
    title: "Automated Brief",
    href: "/automated-revenue-brief",
    icon: "Award",
    description: "BUILD 033 Automated Revenue Brief Engine",
  },
  {
    title: "Dyscyplina Danych",
    href: "/data-discipline",
    icon: "ShieldAlert",
    description: "BUILD 014A Dyscyplina danych leadów",
  },
  {
    title: "Zdrowie Integracji",
    href: "/integrations-health",
    icon: "ShieldAlert",
    description: "BUILD 026A Monitoring statusów integracji",
  },
  {
    title: "Conversion Audit",
    href: "/conversion-audit",
    icon: "LineChart",
    description: "BUILD 028 Audyt konwersji i wycieków lejka",
  },
  {
    title: "Tirana Performance",
    href: "/landing-tirana-performance",
    icon: "LineChart",
    description: "BUILD 029 Monitoring skuteczności landingu Tirana",
  },
  {
    title: "Dashboard CEO",
    href: "/dashboard",
    icon: "LayoutDashboard",
    description: "Przegląd wykonawczy",
  },
  {
    title: "Leady",
    href: "/leads",
    icon: "Users",
    description: "Lejek sprzedażowy",
  },
  {
    title: "Oferty",
    href: "/offers",
    icon: "FileText",
    description: "Aktywne oferty",
  },
  {
    title: "Followupy",
    href: "/followups",
    icon: "CalendarClock",
    description: "Zaplanowane działania",
  },
  {
    title: "Handlowcy",
    href: "/salespeople",
    icon: "UserCheck",
    description: "Wyniki zespołu",
  },
  {
    title: "Modele",
    href: "/models",
    icon: "Home",
    description: "Katalog produktów",
  },
  {
    title: "Inteligencja Marketingu",
    href: "/marketing-intelligence",
    icon: "Megaphone",
    description: "Kampanie Google i Meta Ads",
  },
  {
    title: "Wyciek Pieniędzy",
    href: "/money-leak",
    icon: "TrendingDown",
    description: "Utrata przychodów",
  },
  {
    title: "Martwe Leady",
    href: "/dead-leads",
    icon: "Skull",
    description: "Nieaktywne szanse",
  },
  {
    title: "Wynik CEO",
    href: "/ceo-score",
    icon: "Award",
    description: "Indeks kondycji",
  },
  {
    title: "Słowniki",
    href: "/dictionaries",
    icon: "ShieldAlert",
    description: "Handlowcy i modele",
  },
  {
    title: "Import CSV",
    href: "/import",
    icon: "Upload",
    description: "Importowanie leadów",
  },
];
